
class Event:
    """this is a superclass for any events that might be generated by an
    object and sent to the EventManager
    """
    def __init__(self):
        self.name = "Generic Event"

class TickEvent(Event):
    def __init__(self):
        self.name = "CPU Event"

class QuitEvent(Event):
    def __init__(self):
        self.name = "Quit Event"

class RestartEvent(Event):
    def __init__(self):
        self.name = "Restart Event"

class MoveRequest(Event):
    def __init__(self, direction):
        self.name = "Move request"
        self.direction = direction

class MoveEvent(Event):
    def __init__(self, snake):
        self.name = "Move event"
        self.snake = snake

class MapBuiltEvent(Event):
    def __init__(self, gameMap):
        self.name = "Map Built"
        self.map = gameMap

class GameStartRequest(Event):
    def __init__(self):
        self.name = "Game start request"

class GameStartedEvent(Event):
    def __init__(self, game):
        self.name = "Game Started"
        self.game = game

class MenuDisplayRequest(Event):
    def __init__(self):
        self.name = "Menu display request"

class ApplePlaceEvent(Event):
    def __init__(self, apple):
        self.name = "Apple placed"
        self.apple = apple

class AppleEatenEvent(Event):
    def __init__(self):
        self.name = "Apple eaten"

class ExtendEvent(Event):
    def __init__(self, snake):
        self.name = "Extend Event"
        self.snake = snake

class SnakePlaceEvent(Event):
    def __init__(self, snake):
        self.name = "Snake placed"
        self.snake = snake

class GameOverEvent(Event):
    def __init__(self):
        self.name = "Game over"

class AddPlayerRequest(Event):
    def __init__(self):
        self.name = "Add player request"

class AddComputerRequest(Event):
    def __init__(self):
        self.name = "Add computer request"